# Generated by Django 2.2.13 on 2021-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('project_description', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_status', models.IntegerField(max_length=2)),
            ],
        ),
    ]
